### ISSUE TITLE
Include miscellaneous components in Camel catalog

### ISSUE THREAD

**Issue by christophd** [apache/camel-k-runtime#1029]
Camel components categorized as miscellaneous/other are currently ignored when building the Camel catalog. We should include those components in order to also resolve these artifacts via the catalog.

**Comment by lburgazzoli** [comment]
I don't recall any specific reason to exclude them, I think it at the time the catalog was introduced, the miscellaneous/other where probably things like camel-main and so on.

What component are actually labelled as miscellaneous/other ?

**Comment by christophd** [comment]
The one that made me realize this issue is `camel-jta` and `camel-cloudevents` which is also listed in the Camel Quarkus extensions but has not been part of the catalog

**Comment by christophd** [comment]
In case the Camel dependency is not listed in the catalog Camel K will raise warnings and the runtime is not using the respective Quarkus extension `camel-quarkus-jta` if it is not listed in the catalog. 

The way it is implemented right now the integration will even fail with errors in case the Camel dependency is not listed in the catalog. We are about to change that to raise warnings instead of failing. These are the miscellaneous components that do have a Camel Quarkus extension:

```
attachments
aws-xray
caffeine-lrucache
cloudevents
console
core-cloud
debug
dsl-modeline
groovy-dsl
headersmap
jasypt
java-joor-dsl
jfr
js-dsl
jsh-dsl
jta
knative-consumer
knative-producer
kotlin
kotlin-dsl
leveldb
lra
management
microprofile-fault-tolerance
microprofile-health
openapi-java
opentelemetry
opentracing
reactive-executor-vertx
redis
shiro
smallrye-reactive-messaging
threadpoolfactory-vertx
xml-io-dsl
xml-jaxb
xml-jaxp
yaml-dsl
```

**Comment by squakez** [comment]
I understand this is now completed.
