### ISSUE TITLE
Suport Java 11

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k-runtime#103]

**Comment by ipolyzos** [comment]
According to the [release notes](https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html#JDK-8190378) Java 11 has removed the Java EE modules. When an attempt to compile the latest master on Java 11 there is an issue to resolve the _javax.xml.bind_ package.

[1] 
> $ java -version                                                                                                            
> openjdk version "11.0.3" 2019-04-16 LTS
> OpenJDK Runtime Environment Zulu11.31+11-CA (build 11.0.3+7-LTS)
> OpenJDK 64-Bit Server VM Zulu11.31+11-CA (build 11.0.3+7-LTS, mixed mode)

**Comment by oscerd** [comment]
This issue is not closed indeed

**Comment by davsclaus** [comment]
Does it not work on Java 11 now ?
