### ISSUE TITLE
Knative component switches from POST to GET depending on the presence of the exchange body

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#121]
It should always use POST.

**Comment by lburgazzoli** [comment]
@nicolaferraro can you check that this is solved with the latest code based on undertow ?

**Comment by nicolaferraro** [comment]
Will write some integration tests

**Comment by lburgazzoli** [comment]
I'll add an additional check to validate methods and body

**Comment by lburgazzoli** [comment]
https://github.com/apache/camel-k-runtime/pull/161

**Comment by nicolaferraro** [comment]
Verified in integration tests
