### ISSUE TITLE
Add the error log when setting component property failed

### ISSUE THREAD

**Issue by WillemJiang** [apache/camel-k-runtime#137]
It looks like the groovy component property setting DSL doesn't throw any exception from the runtime when the property name is wrong.  
But when setting the value with method in component with wrong name, the thrown exception is not related to component property setting issue.
So my suggestion is adding error log for it, to help the user to find out the real reason.

**Comment by lburgazzoli** [comment]
Fixed by https://github.com/apache/camel-k-runtime/pull/138
