### ISSUE TITLE
Support explicit source/target in knative endpoint

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#150]
Currently Camel K 1.0.0-M2 has a pre-baked list of allowed endpoints that can be used as start or end of a route.

E.g.

```
from('knative:channel/xx`)
```

The Knative trait looks for:
- `eventing.knative.dev/v1alpha1 -> Channel`
- `messaging.knative.dev/v1alpha1 -> Channel`
- `messaging.knative.dev/v1alpha1 -> InMemoryChannel`
- `messaging.knative.dev/v1alpha1 -> KafkaChannel`
- ...

A similar thing happen for the `knative/endpoint`.

It would be better if a user can explicitly set the target, like:

```
from('knative:channel/xx?kind=InMemoryChannel')
```

or even:
```
from('knative:channel/xx?kind=InMemoryChannel&apiVersion=messaging.knative.dev/v1')
```

Same also for `endpoint`. In the case of channel, the operator creates also a subscription.

The resolution of the apiVersion and kind will happen at operator level, but those properties need to be accepted by the runtime.

Wdyt @lburgazzoli ?

**Comment by lburgazzoli** [comment]
A simple solution would be to make the endpoint to allow unknown options, would that be ok ?

**Comment by nicolaferraro** [comment]
Not sure.. I'm worried about @valdar making typos at next conference and not getting an error back :)

**Comment by lburgazzoli** [comment]
So I will add such info even if we throw them away :)
