### ISSUE TITLE
Support Knative broker/trigger model

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#151]
We can add a third endpoint to knative called `events`.

A user can write:

```
from('knative:events/chuck.norris')
```

To get all events of type `chuck.norris`.
The behavior will be:
- The operator creates a trigger on event type `chuck.norris`
- The component filters messages containing header `Ce-Type` equals to `chuck.norris`
- The component exposes the usual endpoint to receive cloud events

Some additional properties are required:
- `brokerApiVersion`: to change the api version of the broker (interpreted by the operator)
- `brokerName`: to change the name of the broker to use (by default there's only one called default)
- brokerKind cannot be changed as there's a single CRD at the moment

Additional filters can be put in the endpoint, e.g.:

```
from('knative:events/chuck.norris?ceAuthorName=Nicola')
```

`ceAuthorName` like filters can be dynamic and translate into an additional filter on both the trigger and the component on the header `Ce-Author-Name`.

**Comment by lburgazzoli** [comment]
About the additional filtering part, we can re-use what we have as today so like:

    from('knative:events/chuck.norris?filter.ceAuthorName=Nicola')
