### ISSUE TITLE
Switch to CloudEvents 0.3

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#154]
We should evaluate switching to the CE library in future releases (> M3).

There are some specific things that it handles better, like content type and support for claim check that we may leverage (https://cloudevents.io/#v03)

**Comment by lburgazzoli** [comment]
Relates to https://github.com/apache/camel-k-runtime/issues/105

**Comment by lburgazzoli** [comment]
the cloud event sdk seems overcomplicated for our needs

**Comment by lburgazzoli** [comment]
https://github.com/apache/camel-k-runtime/pull/158
