### ISSUE TITLE
Ad a specific section in the camel-k-runtime catalog to list loaders and related dependencies

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k-runtime#182]
As today we do hard-code loaders dependencies in camel-k but as that's really tight to camel-k-runtime, we should add a section in the camel-k-runtime generated catalog to list the dependency for each loader/language we support.

see: https://github.com/apache/camel-k/blob/465444d0234bd72ce9cd8a06e1571a5d236bd594/pkg/trait/dependencies.go#L47-L85

**Comment by davsclaus** [comment]
Should we remove support for java class? eg we talked about that in the past and using a pre compiled class was not recommended / dont work in many cases etc

**Comment by lburgazzoli** [comment]
Will remove it

**Comment by lburgazzoli** [comment]
done in https://github.com/apache/camel-k-runtime/pull/231
