### ISSUE TITLE
Native support for CronJob: convert cron endpoints to fire once at startup

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#222]
Related to https://github.com/apache/camel-k/issues/1182

We should implement via a pluggable runtime module a customizer/loader that, when activated, makes sure an integration fires a single execution of every `timer` or `quartz` consumers at startup and immediately shutdown everything after the exchange is processed.

**Comment by lburgazzoli** [comment]
We should probably introduce a concept of source customizer/trait so we can apply multiple traits to ta source in a consistent way

**Comment by davsclaus** [comment]
Just mind if the user has both a timer/quartz route and a non cron like route in the same integration? I guess we need to check that this is the only route.

Also you can set camel main, the max number of messages to process (eg set it to 1 to have camel main terminate after that 1 message).

**Comment by lburgazzoli** [comment]
Yes we do something similar for the `knative-source` where we fail if there is more than one route. Unfortunately the camel-main do not yet support exit the application in camel-quarkus (we need quarkus command mode to be implemented for that)
