### ISSUE TITLE
[quarkus] support stopping the application

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k-runtime#224]
Depends on https://github.com/quarkusio/quarkus/issues/6498

**Comment by lburgazzoli** [comment]
Requires Quarkus 1.4.x
Docs: https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/command-mode-reference.adoc

**Comment by ToWipf** [comment]
Is this a good way to stop the application?
```
	private boolean bShutdown = false;

	@Override
	public int run(String... args) throws Exception {
		LOGGER.info("start");
		while (true) {
			Thread.sleep(1000);
			if (bShutdown) {
				LOGGER.info("stop");
				return 0;
			}
		}
	}

	public void stopApp() {
		this.bShutdown = true;
	}
```

**Comment by lburgazzoli** [comment]
Requires https://github.com/apache/camel-quarkus/issues/1128
