### ISSUE TITLE
add support for routes loaders interceptors

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k-runtime#227]
I want to introduce some new parameters to the source definition to define the interceptors that have to be executed while loading a route with methods like:

```java 
interface RouteLoaderInterceptor {
    /**
     * Invoked before the source is materialized top a RoutesBuilder.
     */
    void beforeLoad(Loader, Source);
    /**
     * Invoked after the source is materialized to a RoutesBuilder and before
     * the builder is added to the runtime.
     */
    void afterLoad(Loader, Source, RoutesBuilder);
}
```

the goal is to be have a clean APIs to implement functionalities such as those provided by the knative-source loader and the cron customizer.

On camel-k side, the source should amended like:

```go
type SourceSpec struct {
    DataSpec
    Language Language `json:"language,omitempty"`
    // Loader is an optional id of the org.apache.camel.k.RoutesLoader that will
    // interpret this source at runtime
    Loader string `json:"loader,omitempty"`
    // List of interceptors required by this source
    Interceptors []string `json:"interceptors,omitempty"`
}
```

**NOTE**: the knative-loader and cron customizer won't be removed but marked as deprecated.

@nicolaferraro tough ?

**Comment by nicolaferraro** [comment]
Sounds good!
The knative loader is actually not a loader but an interceptor in practice

**Comment by lburgazzoli** [comment]
update the `SourceSpec` definition as seems better to use IDs to identify interceptors instead of giving the options to also use the class name

**Comment by lburgazzoli** [comment]
requires camel 3.1.x
