### ISSUE TITLE
camel-k-loader-xml - Use camel-xml-io for loading XML

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k-runtime#246]
Its not using JAXB and its much more lightweight and faster.

This requires Camel 3.1 onwards.

**Comment by davsclaus** [comment]
See the tiny-xml example
https://github.com/apache/camel-examples/blob/master/examples/camel-example-main-xml/pom.xml#L59

**Comment by lburgazzoli** [comment]
Added to the to do list for the upgrade to Camel 3.1 (#245)
