### ISSUE TITLE
Add capabilities to catalog

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k-runtime#248]
Depending on the platform, some capabilities are provided through different artifacts, as example, health endpoint are implemented through mp health whereas on camel-main, the camel-k-runtime provides its own implementation.

The runtime section of the catalog should provide info about what artefacts are used to implement additional features

**Comment by nicolaferraro** [comment]
I'm wondering if we should do the same reasoning for rest provider. We have a default for mp and for camel main there are many, but we can choose one to be the default, so that people don't have to choose one..

**Comment by lburgazzoli** [comment]
good point, yes it does make sense
