### ISSUE TITLE
Add circuit-breaker capability

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k-runtime#257]
So we do not hard-code camel-histrix on camel-k-side

**Comment by davsclaus** [comment]
There are 3 implementations now
- hystrix
- resilience4j
- microprofile-fault-tolerance

The last one is in Camel 3.3 onwards.

**Comment by davsclaus** [comment]
And microprofile-fault-tolerance should be default if anyone (as hystrix is deprecated)
