### ISSUE TITLE
Quarkus application becomes ready before routes are bound

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#262]
Running the example here: https://github.com/nicolaferraro/api-demo

When running with `-t quarkus.enabled=true`, the `api` integration is considered ready by Kube/Istio before the routes are bound.

So:
- Wait for the integration to scale down to 0
- Push some data
- The integration is scaled up
- But `404` is received

```
[nferraro@localhost nicolaferraro]$ curl -i -X POST --header "Content-Type: application/octet-stream" --data-binary "@/path/to/img.png" http://api.nicola-tests.cluster-url.org/
HTTP/1.1 100 Continue

HTTP/1.1 404 Not Found
content-length: 53
content-type: text/html; charset=utf-8
date: Thu, 12 Mar 2020 15:38:40 GMT
x-envoy-upstream-service-time: 13080
server: istio-envoy
Set-Cookie: 5edb8a63d369aa9120a27bc3a0ddfa2c=58efd7ebbb54fe47bba304ed22ae6ad9; path=/; HttpOnly
```

The same integration without the Quarkus trait works well.

**Comment by lburgazzoli** [comment]
I think we need to split the readiness and liveness probes in general so we probably need to add the health trait but don't know if it will work out of the box

**Comment by davsclaus** [comment]
In camel 3.4 the microprofile-health is divided into ready and liveness. However out of the box then all the checks are readiness.

And when we enable quarkus trait, do we automatic add the microprofile-health extension so health check is included?
