### ISSUE TITLE
Release 0.3.1

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#28]
There are some bugfixes and improvements in the Knative area that deserve a new release:
- Fix knative service call (https://github.com/apache/camel-k-runtime/pull/20)
- Use cloudevents 0.2 (https://github.com/apache/camel-k-runtime/pull/25)
- Support for health checks (https://github.com/apache/camel-k-runtime/pull/22, https://github.com/apache/camel-k-runtime/pull/24)
- Fix catalog (https://github.com/apache/camel-k-runtime/pull/26)

**Comment by oscerd** [comment]
+1

**Comment by lburgazzoli** [comment]
+1

**Comment by lburgazzoli** [comment]
done
