### ISSUE TITLE
Add an opentracing capability

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#289]
It's currently possible to configure opentracing via quarkus using instructions from https://camel.apache.org/camel-quarkus/latest/extensions/opentracing.html#_usage.

Running the integration with command:
```
kamel run Example.java -t quarkus.enabled=true -d mvn:org.apache.camel.quarkus:camel-quarkus-opentracing --property-file application.properties
```

But it uses quarkus properties and the same feature is not available in plain main.

I wonder if this is a case for adding a capability.
I don't know also if we can uniform those properties between environments.

**Comment by lburgazzoli** [comment]
Adding a capability is definitively easy but harmonizing the properties could be a very hard and fragile work as quarkus may introduce new properties and we also need to distinguish between build and runtime ones.

I think one day we may default to quarkus as runtime ....
