### ISSUE TITLE
Add a way to easily call a bean method after camel has started

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k-runtime#324]
so you dont have to do the timer:foo?repeatCount=1 trick.

Some kind of annotation or convention method name or something. We do have some event listeners we can hook into. But lets consider making this easy for end users writing their camel k in a source file in java / groovy etc.

**Comment by lburgazzoli** [comment]
Wonder if we should do this through @BindToRegistry like:

```java
@BindToRegistry
OnStart doOnStart() {
    return context -> doSomething(context);
}
```

so we can use the same thing also for groovy/kotlin

```kotlin
beans {
    bean<OnStart>("doOnStart") {
        doSomething(it)
    }
}
```

**Comment by davsclaus** [comment]
Yeah possible. I was also considering something even easier, with just a special method name or something. As otherwise you have to juggle with all that lambda and annotations.

When all you wanted was just to have a method on RouteBuilder that camel-k would call.

```
public void onStartup() {
  ... here you can do whatever you want.
  .. you can access context
}

public void configure() {
   ... here is the route builder dsl
}
```

**Comment by lburgazzoli** [comment]
Maybe having an interface to extend ? I'm more keen to have a property type to have better support for tooling so i.e for plain Java you can do something like

```java
class MyRoute extends RouteBuilder implements OnStartup {
    public void onStartup() {
    }
}
```

This would also allow the runtime to easily detect what to do without having to rely on reflection to access methods, so when a route is added, camel-k runtime can do something like:

```java
if (route instanceof OnStartup) {
    context.addLifecycleStrategy(...);
}
```

and for scripting

```groovy
context {
    onStartup {
        ....
    }
}

**Comment by davsclaus** [comment]
The `RouteBuilder` could also have a `onStartup` method already so you just need to override it. But the interface is also a good way as its a very common pattern

**Comment by lburgazzoli** [comment]
Or maybe we can just enrich the RouteBuilder DSL to have a `onStartup`, `onShutdown` method so you can write something like:

```java
public void configure() {
   onStartup(this::doOnStartup);
}
```

That would be agnostic of the runtime

**Comment by lburgazzoli** [comment]
Fixed on came by https://github.com/apache/camel/pull/3850
