### ISSUE TITLE
Switch to Quarkus as runtime 

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k-runtime#359]

**Comment by lburgazzoli** [comment]
@davsclaus @nicolaferraro should we do the switch for this milestone or for 1.5.0 ?

**Comment by davsclaus** [comment]
I am okay switching now

**Comment by lburgazzoli** [comment]
@davsclaus @nicolaferraro 

I guess we could default to quarkus for camel-k 1.1.0 (runtime 1.4.0) but keep main as an option and mark it as deprecated, then fully drop main in camel-k 1.2.0 (runtime 1.5.0)

**Comment by nicolaferraro** [comment]
> @davsclaus @nicolaferraro
> 
> I guess we could default to quarkus for camel-k 1.1.0 (runtime 1.4.0) but keep main as an option and mark it as deprecated, then fully drop main in camel-k 1.2.0 (runtime 1.5.0)

Sounds perfect, let's move the complete removal of the main to 1.5.0.

**Comment by lburgazzoli** [comment]
Done with https://github.com/apache/camel-k-runtime/pull/543
