### ISSUE TITLE
Include description for elements in Yaml schema

### ISSUE THREAD

**Issue by apupier** [apache/camel-k-runtime#386]
it will allow to have information on completion and on hover in all IDEs supporting the Yaml language server.

not trivial as @lburgazzoli commented:

> it[the description] was supposed to be there but I removed  it since that information is not always available in the annotation but it is something on the method and I don't have yet a clean solution to grab such info.

**Comment by apupier** [comment]
@nicolaferraroyou mentioned that the genration of Yaml dsl was modified between 1.3.0 and 1.4.0. Do you know if it is changing something to implement this feature? would it be simpler?

**Comment by lburgazzoli** [comment]
Moved to main apache camel project https://issues.apache.org/jira/browse/CAMEL-16650

**Comment by apupier** [comment]
@lburgazzoli Can you clarify the link with the mentioned [issue](CAMEL-16650) in Camel tracker?

Th egoal is this created issue is to have description provided in the json schema for the yaml dsl.
The pointed issue is mentioning the loading of kamelets from different places.

**Comment by lburgazzoli** [comment]
link fixed
