### ISSUE TITLE
knative: refactor knative environment definition

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k-runtime#453]
As today the knative json definition looks like:

```json
{
    "services": [
        {
             "type": "channel|endpoint|event",
             "name": "",
             "host": "",
             "port": "",
             "metadata": {
                 "service.path": "",
                 "service.url" : "",
                 "filter.header": "value",
                 "knative.event.type": "",
                 "knative.kind": "",
                 "knative.apiVersion": "",
                 "camel.endpoint.kind": "source|sink",
                 "ce.override.ce-type": "something",
             }
        }
    ]
}
```

but:
1. to avoid confusion, the `services` array should be renamed to `resources`
2. to make the component transport agnostic, host and port should be deprecated and removed
3. `service.url` should be promoted as field used to describe the target resource (replace host & port)
4. `service.path` should be removed
5. should the `endpoint` type be renamed to `service` ?

We can keep the fields still presents for a release cycle.

**Comment by lburgazzoli** [comment]
@nicolaferraro does it make sense for you ?

**Comment by nicolaferraro** [comment]
Everything ok, except renaming endpoint to service because endpoint can be used not only with (Knative) service but with any kind of endpoint.

Is service.url already supported?

**Comment by lburgazzoli** [comment]
> Everything ok, except renaming endpoint to service because endpoint can be used not only with (Knative) service but with any kind of endpoint.
> 

What other endpoint do you have in mind ?

> Is service.url already supported?

Yes, I think you are already setting it :)

**Comment by lburgazzoli** [comment]
So `service.path` can't be removed as may be needed to set the listening path as when using the `platform-http` there may be a risk to clash with other services being exposed on the same port
