### ISSUE TITLE
Remove suport for "configuration" classes

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k-runtime#480]
As today, the runtime supports loading configuration classes written in Java so as example:

```java
class MyBeans {
    @BindToRegistry
    Processor myProcessor() {
        return ...;
    }
}
```

Those kind of classes may be sometime useful but given that we want to focus on the routes and that if needed such classes can be provided by a jar and referenced through camel-main's configuration properties, I'm proposing to drop them which has the nice side effect to dramatically simplify the code and allow to contribute the source loading mechanics to Camel.

Using `@BindToRegistry` and other annotations will of course be possible on `RouteBuilder` classes.

**Comment by lburgazzoli** [comment]
@nicolaferraro @davsclaus what do you think ?

**Comment by davsclaus** [comment]
Fine with me, less special camel-k then maybe better
