### ISSUE TITLE
kamelet-sink component

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k-runtime#490]
Wonder if we can think of using something else than direct:route-id in kamelets when its a sink
See bottom at: https://camel.apache.org/camel-k/latest/kamelets/kamelets.html

Should we introduce a kamelet-sink endpoint or something? (can facade direct)

**Comment by lburgazzoli** [comment]
I was looking at implementing this but with camel 3.x you cannot use any more the scheme only so as example:

```yaml
from:
  ...
  steps:
    - to: "kamelet-sink"
```

Won't work.

It would be possible to write something like `kamelet-sink:foo` but then the path param `foo` won't have any real meaning which could be confusing so one should write `kamelet-sink:{{routeId}}` ?

**Comment by nicolaferraro** [comment]
I remember we talked about this ~2 years ago... and the component was called like "template:placeholder".

**Comment by nicolaferraro** [comment]
We can force usage of that exact syntax, without free path.

**Comment by davsclaus** [comment]
you can also use the existing kamelet component let let "sink" be reserved for this use-case

    to: "kamelet:sink"

**Comment by lburgazzoli** [comment]
interesting
