### ISSUE TITLE
Release 0.3.2

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#51]
We should start a new minor release in order to have the following fixes:

- add catalog information to runtime artifacts
- fix stream handler
- fix netty http binding for knative
- support stream caching configuration
- honour cutomizer list property/env
- add a default type to cloudevents
- deprecation of spring-boot runtime https://github.com/apache/camel-k/issues/534

In particular, without the fixes to the knative component, Knative CamelSources are not usable.

**Comment by oscerd** [comment]
+1

**Comment by lburgazzoli** [comment]
I would inlcude deprecating spring-boot support (see https://github.com/apache/camel-k/issues/534)

What do you think ?

**Comment by nicolaferraro** [comment]
I've already cut a release, but we can add deprecation of spring-boot to the release notes. I don't think we need to do something concrete.

**Comment by nicolaferraro** [comment]
Released.
