### ISSUE TITLE
Allow to programmatically enable a route

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#540]
Currently routes are loaded via properties, e.g.:

```properties
camel.k.sources[0].location=file:/etc/camel/sources/i-source-000/display.groovy
camel.k.sources[0].name=display
camel.k.sources[0].language=groovy
```

I was thinking to add a property like:

```properties
camel.k.sources[0].enabled=false
```

That could be used to enable/disable a route (default `true`).

I'd use that in the operator this way:

```properties
camel.k.sources[0].enabled={{hostname-matches:display-0}}
```

Where `hostname-matches` is a property-function (we should define it in the runtime), that evaluates to true or false depending on the current name of the pod (`HOSTNAME` env variable).

This can allow us to assign partition keys to various pods in a StatefulSet.
I'm open to alternatives :D.

**Comment by lburgazzoli** [comment]
you mean not to  load the route source entirely ?

**Comment by nicolaferraro** [comment]
Yes, that was the purpose. Which also may simplify the monitoring part because routes will run only once in a cluster.

**Comment by nicolaferraro** [comment]
Not needed after this is merged: https://github.com/apache/camel/pull/4662
