### ISSUE TITLE
Kamelet component - optimize as we did for direct component

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k-runtime#544]
In camel 3 we optimized the direct component. We should do the same for kamelet component as it is a copy of direct with a few other changes.

**Comment by lburgazzoli** [comment]
@davsclaus quarkus work has been merged, when you have time, feel free to have a look

**Comment by davsclaus** [comment]
Yeah I should have time tomorrow and this can be done on camel 3.6 (I think)
