### ISSUE TITLE
Catalog contains duplicate entry for same schema (cron)

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#592]
See: https://github.com/apache/camel-k/issues/1939#issuecomment-765560895

cc: @lburgazzoli

**Comment by lburgazzoli** [comment]
is that true also for the master component ?

**Comment by nicolaferraro** [comment]
> is that true also for the master component ?

Yes. I think we can add a guard to fail in case of duplicate schemas.
Also for master the capability contains reference to the runtime part.

**Comment by lburgazzoli** [comment]
I think we have two options here:

1. since `camel-k-master` and `camel-k-cron` have transitive dependencies on the related camel-quarkus components, we can ignore the camel-quarkus ones when when the catalog is computed (so camel-k-runtime ones have higher priority) 
2. do not add schemes to camel-k-runtime artefact as they are used to provide capabilities

@nicolaferraro @astefanutti what do you think ?

**Comment by nicolaferraro** [comment]
> I think we have two options here:
> 
> 1. since `camel-k-master` and `camel-k-cron` have transitive dependencies on the related camel-quarkus components, we can ignore the camel-quarkus ones when when the catalog is computed (so camel-k-runtime ones have higher priority)
> 2. do not add schemes to camel-k-runtime artefact as they are used to provide capabilities
> 
> @nicolaferraro @astefanutti what do you think ?

I'm not sure they have transitive dependencies, actually iirc the CI was failing when the runtime version of the artifacts was chosen.

Yeah, `camel-k-cron` does not seem to depend on `camel-quarkus-cron`.

**Comment by nicolaferraro** [comment]
I'd do option 2 so.

**Comment by lburgazzoli** [comment]
> > I think we have two options here:
> > 
> > 1. since `camel-k-master` and `camel-k-cron` have transitive dependencies on the related camel-quarkus components, we can ignore the camel-quarkus ones when when the catalog is computed (so camel-k-runtime ones have higher priority)
> > 2. do not add schemes to camel-k-runtime artefact as they are used to provide capabilities
> > 
> > @nicolaferraro @astefanutti what do you think ?
> 
> I'm not sure they have transitive dependencies, actually iirc the CI was failing when the runtime version of the artifacts was chosen.
> 
> Yeah, `camel-k-cron` does not seem to depend on `camel-quarkus-cron`.

That is likely to be a leftover of the migration to quarkus as the runtime, it needs to be fixed in any case

**Comment by astefanutti** [comment]
To the best of my _limited_ knowledge, it seems more logical to me that camel-k-runtime artifacts do **not** declare schemes, so I'd go for 2 as well.
