### ISSUE TITLE
PR actions failing

### ISSUE THREAD

**Issue by squakez** [apache/camel-k-runtime#626]
PRs are failing because `No such image: testcontainers/ryuk:0.3.0`. It seems related to this [issue](https://github.com/testcontainers/testcontainers-java/issues/3574).

This should be fixed by using testcontainers version `1.15.1` instead of `1.15.0`. Dependency is updated in camel `3.8.0` but not in `3.7.0`, so likely we should have this fixed when bumping the camel version.

**Comment by lburgazzoli** [comment]
You can bump the version in this project, see: https://github.com/apache/camel-quarkus/commit/e59a7bd2f07398c525040e3315107ea5719f16dc

**Comment by squakez** [comment]
This was fixed via #627. However I'd keep it open in order to remove the overridden dependencies once we bump `camel-quarkus` and `camel` version to versions that are using the updated testcontainers.
