### ISSUE TITLE
Examples broken after the quarkus 1.7.0 update

### ISSUE THREAD

**Issue by tplevko** [apache/camel-k-runtime#641]
I tried to run the examples following the README-s attached, but none I tried (java, cron, groovy) seem to work.

What I observed: 
* the commit to break the functionality seems to be https://github.com/apache/camel-k-runtime/commit/b31ade248092ecd15a45dc52a0b8e122e8951e7f
* there are the ${example-name}-runner.jar missing in the target directory after the examples are built

@lburgazzoli can you have a look?

**Comment by lburgazzoli** [comment]
Fixed by #643
