### ISSUE TITLE
Update runtime to Camel 3.10 and Camel Quarkus 2.x

### ISSUE THREAD

**Issue by orpiske** [apache/camel-k-runtime#669]
Now that 3.10 is out, we need to update the runtime to use the newer version. 

- [x] Create work branch for Camel 3.10 + Camel Quarkus 1.9 development
- [x] Upgrade to Camel 3.10 + Camel Quarkus 1.9
- [x] Upgrade to Camel Quarkus 2.x
- [x] Resolve #667 
- [x] Resolve #657 
- [x] Verify #625
- [x] Fix test issue #687

**Comment by oscerd** [comment]
We need camel Quarkus released first

**Comment by orpiske** [comment]
Indeed! Let me add list of items so we can keep track of that

**Comment by orpiske** [comment]
@oscerd Currently, I wonder if we should create a branch to keep the runtime aligned w/ Camel Quarkus devel. Similarly to what we used to have with camel-master on CKC, but without any automation (as it seems to me we the changes are quite extensive).

I have some initial changes to do that - not sure to what extent it is functional - but could be a starting point. 

Wdyt?

**Comment by orpiske** [comment]
Also mentioning @nicolaferraro @squakez @lburgazzoli @astefanutti and everyone else insights.

**Comment by oscerd** [comment]
I think it makes sense to notice problem earlier

**Comment by lburgazzoli** [comment]
once upon a time there were a ci-build-camel-master workflow that was supposed to do something similar

**Comment by orpiske** [comment]
@oscerd @lburgazzoli Thanks guys. So, I guess we can create branch "camel-main" and kick that work in there. Alright? I volunteer to kick off that work. 

@oscerd do you know if we can create branches or do we have to request infra?

**Comment by oscerd** [comment]
You can simply push a new branch. No need for infra

**Comment by orpiske** [comment]
@oscerd fantastic. 

@oscerd @lburgazzoli what do you guys prefer? Move or new? It doesn't matter to me.

**Comment by orpiske** [comment]
Hm, nevermind, I think it doesn't matter. I'll take a look and try to move it. Otherwise I'll create a new one.

**Comment by oscerd** [comment]
I think it makes sense to remove it and create a new one maybe

**Comment by squakez** [comment]
We must verify also this issue is no longer standing #625. You may edit the issue description and add also this one not to forget about it (you can assign it to me as well).

**Comment by orpiske** [comment]
@squakez thanks! I added that one to the list.

**Comment by squakez** [comment]
#625 correctly verified and closed. You can tick the related box :)

I can work and verify #657 as well.

**Comment by squakez** [comment]
Also #657 verified correctly.

**Comment by orpiske** [comment]
I'm marking this one as done. We may have a few specific 3.10 items such as #706 and others, but the bulk of the work is complete.
