### ISSUE TITLE
Set YamlDeserializationMode.FLOW on camel-context

### ISSUE THREAD

**Issue by oscerd** [apache/camel-k-runtime#707]
To be able to do something like:

https://github.com/apache/camel/blob/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/SplitTest.groovy#L62-L87

And have a filtering step without the need of having a to in the same step, we need to set the YamlDeserializationMode to FLOW.

For 3.10.0/1.9.0/1.5.0 we may create an option to enable it, with 3.11.0 we should make it the default.

cc @lburgazzoli @nicolaferraro

**Comment by lburgazzoli** [comment]
https://issues.apache.org/jira/browse/CAMEL-16693

**Comment by lburgazzoli** [comment]
fixed
