### ISSUE TITLE
Move components to Camel

### ISSUE THREAD

**Issue by squakez** [apache/camel-k-runtime#752]
Follow up issue to remind to move the [components](https://github.com/apache/camel-k-runtime/tree/main/components) to Camel.

cc @lburgazzoli feel free to include any further hint or description for this task.

**Comment by davsclaus** [comment]
Yes we should move them over as part of Camel 3.15 release

**Comment by davsclaus** [comment]
components has been ported to Camel 3.15
https://github.com/apache/camel/commit/d7d1e6c958335e03d764376c36fc630a61e106a8

After the 3.15 release we can then in camel-k-runtime delete ours and use the ones from camel

**Comment by oscerd** [comment]
This has been done through #793
