### ISSUE TITLE
Move dsl-jsh to core project

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k-runtime#767]
We can port over the javashell DSL to the core camel project so we have all of them together. This DSL will still be experimental, but since its standard Java Shell then it can have more potential than the joor java library we use for Java DSL

**Comment by davsclaus** [comment]
Moved over in Camel 3.15 onwards
https://issues.apache.org/jira/browse/CAMEL-17382

**Comment by oscerd** [comment]
Do we have to remove the dsl-jsh?

**Comment by davsclaus** [comment]
Yes remove after upgraded to Camel 3.15. 

On the camel-k side then it may need to understand that running integrations with jsh extension should pick the new GAV from camel core project and not camel-k-runtime

**Comment by davsclaus** [comment]
The same for the other DSLs as they have been ported to the core camel project in the dsl folder.

**Comment by oscerd** [comment]
What dsl needs to be removed?

**Comment by davsclaus** [comment]
https://github.com/apache/camel-k-runtime/tree/main/camel-k-loader-jsh

**Comment by davsclaus** [comment]
Yes we have done that for the other DSLs like Kotlin, Groovy etc

**Comment by oscerd** [comment]
ok, sounds good then

**Comment by oscerd** [comment]
I think there will be troubles with the itests, because we don't have an extension for camel-quarkus-jsh-dsl

**Comment by oscerd** [comment]
Ah no, I was missing the loader-inspector dep. Nevermind.
